### ISSUE TITLE
Issues with UTF-8 encoding in emails

### ISSUE THREAD

**Issue by sirupsen** [campaignmonitor/createsend-ruby#19]
Hi,

Reading the source and the CampaignMonitor documentation it's quite clear that it accepts UTF-8 encoded data. However, the following script does not work with `createsend-ruby`:

``` ruby
#encoding=utf-8
require 'createsend'
CreateSend.api_key '<snip>'

puts CreateSend::VERSION

CreateSend::Subscriber.add('<snip>', "jøsses@bådbasæn.dk", "Tester", [], false)
```

Trace:

``` ruby
1.1.1
/Users/sirup/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/createsend-1.1.1/lib/createsend.rb:141:in `handle_response': The CreateSend API responded with the following error - 1: Please provide a valid email address. (CreateSend::BadRequest)
        from /Users/sirup/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/createsend-1.1.1/lib/createsend.rb:134:in `post'
        from /Users/sirup/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/createsend-1.1.1/lib/createsend/subscriber.rb:30:in `add'
        from hej.rb:7:in `<main>'
```

It works fine with special characters in the name. I wrote to CampaignMonitor support as well to ask finally if they accept special characters in email (as they should).

**Comment by thejspr** [comment]
@Sirupsen what was the solution to this problem? I'm having the exact same issue.

**Comment by Sirupsen** [comment]
@thejspr I don't remember :( It's been too long. Perhaps @mkyed can grep the code if we still use Campaign Monitor?

**Comment by mkyed** [comment]
We do not do anything special to support utf-8 characters but have had no complaints about it either :smile:  I guess the best way to work around it is to IDN/punycode convert the email address before sending it to CM.

**Comment by thejspr** [comment]
Thanks @Sirupsen and @mkyed. CM does indeed not support non-latin characters in emails so there is not much to do but handling the raised exception.
