### ISSUE TITLE
SegmentIDs ignored when creating a new Campaign

### ISSUE THREAD

**Issue by jerodsanto** [campaignmonitor/createsend-ruby#39]
Howdy!

I'm trying to send two emails via the API, one with a day theme and one with a night theme. I have the appropriate segments set up on my list, but when I make the API call it ignores the `SegmentIDs` and sends to the entire list. Here is the JSON payload that is being sent:

```json
{
 "Subject": "The Hottest Repos on GitHub - Mar 08",
 "Name": "Nightly – Mar 08 (day theme)",
 "FromName": "Changelog Nightly",
 "FromEmail": "nightly@changelog.com",
 "ReplyTo": "editors@changelog.com",
 "HtmlUrl": "http://nightly.thechangelog.com/2015/03/08/email-day.html",
 "TextUrl": null,
 "ListIDs": ["1cf7c272705e97f1be3d49acd2d82cd8"],
 "SegmentIDs": ["26098f2c17ae0f62acb49690785477e1”]
}
```

You can see the exact code I'm using to generate this payload in our repo, [right here](https://github.com/thechangelog/nightly/blob/themes/Rakefile#L106-L126).

Any idea why the segments aren't being picked up? Thanks!

**Comment by itgoeslikethis** [comment]
Hi @jerodsanto - the reason it's sending to the list, is because you've included the ListID in the array:
`"ListIDs": ["1cf7c272705e97f1be3d49acd2d82cd8"]`
For targeting a segment, all you need is the SegmentID. If you don't want it sending to a whole list, then send an empty `ListIDs` array:
```
{
 "Subject": "The Hottest Repos on GitHub - Mar 08",
 "Name": "Nightly – Mar 08 (day theme)",
 "FromName": "Changelog Nightly",
 "FromEmail": "nightly@changelog.com",
 "ReplyTo": "editors@changelog.com",
 "HtmlUrl": "http://nightly.thechangelog.com/2015/03/08/email-day.html",
 "TextUrl": null,
 "ListIDs": [],
 "SegmentIDs": ["26098f2c17ae0f62acb49690785477e1”]
}
```

**Comment by jerodsanto** [comment]
@itgoeslikethis ahh, that makes sense I suppose. I figured you'd have to tell it which list and then which segments on that list as well. Perhaps an opportunity to improve the docs?

Thanks for the quick response!

**Comment by itgoeslikethis** [comment]
Hi @jerodsanto , i just noticed you're from the changelog. Nice one! I've listened a few times and enjoyed it.

Yeah the ListIDs and SegmentIDs are directly related to the way sending to lists and segments works in the application; you can specify that your campaign will be sent to any combination of lists and segments, and if an email appears in any of them it'll receive the campaign.

You're not the first person to make this assumption though, so it definitely is an opportunity to improve the docs. I'll have a think about some wording.

**Comment by jerodsanto** [comment]
@itgoeslikethis :+1: thanks for the kind words. In addition to the podcast, we run a [Weekly](http://thechangelog.com/weekly) and [Nightly](http://thechangelog.com/nightly) email through Campaign Monitor and we :green_heart: you guys!

I didn't realize that you can send to both lists _and_ segments with a single campaign. (I also can't think of why you'd want to do that, but I'm sure people have their reasons!)

Feel free to ping me after you update the docs and I'll give you feedback from an outsider's perspective. That way you can _know_ that you drilled it. :beers:
