### ISSUE TITLE
Authentication using API key only isn't working

### ISSUE THREAD

**Issue by joshnabbott** [campaignmonitor/createsend-ruby#43]
I'm following this very basic example using the API key I retrieved from my account settings.

require 'createsend'
cs = CreateSend::CreateSend.new :api_key => 'your api key'
clients = cs.clients

And it always results in this error:
CreateSend::Unauthorized: The CreateSend API responded with the following error - 50: Must supply a valid HTTP Basic Authorization header

Does the API no longer support key based authentication?

**Comment by tolgap** [comment]
@joshnabbott Could you post how you resolved this?

**Comment by lenart** [comment]
Check that you're using API secret (not API key) to authenticate.

```ruby
list = CreateSend::List.new({ api_key: "your-api-secret-here" }, "put-your-list-id-here")
list.details # => { "ListID" => "12345", ... }
```

**Comment by mjwills** [comment]
@Faisal-nfl https://help.createsend.com/admin/api-keys may be of assistance.
