### ISSUE TITLE
The CreateSend API responded with the following error - 101: Invalid ListID

### ISSUE THREAD

**Issue by koolfreak** [campaignmonitor/createsend-ruby#44]
Hi,
I try to add subcriber like this:
list_id = '....'
email_address = CreateSend::Subscriber.add auth, list_id, "subscriber@example.com", "Subscriber", [], true

I am sure i have the correct list from the campaign monitor and also try this solution https://www.campaignmonitor.com/forums/topic/7279/error-invalid-listid101/

but nothing works for me.
Any idea thanks.

**Comment by kg6zgj** [comment]
I seem to be having the same issue.

**Comment by asadighi** [comment]
Hi,

Thanks for reaching out. My name is Aidin and I am the Technical Lead for Integrations and APIs in Campaign Monitor. I would be more than happy to help out.

Do you still experience this issue?

Thanks,
Aidin

**Comment by koolfreak** [comment]
hi, it is already working. thanks

**Comment by Aparee20** [comment]
hi I am not  able to download all the active subscribers  from the list

 ls1 = List({'api_key': 'XXXX'},'XXXXX')
active_sub = ls1.active()
for x in active_sub():
   print x


says  object not iterable , can you please help

**Comment by mjwills** [comment]
The `ListID` that you are using - how did you get that ID @Aparee20 ?
