### ISSUE TITLE
Subscriber.import args

### ISSUE THREAD

**Issue by plainlystated** [campaignmonitor/createsend-ruby#64]
What's the correct way to build a list of subscribers for `Subscriber.import`?  I would expect there to be an initializer for Subscriber along the lines of:

```
Subscriber.new(email_address, name, custom_fields, resubscribe, consent_to_track, restart_subscription_based_autoresponders)
```

... which I would then pass along to `Subscriber.import`.

The only initializer for Subscriber doesn't take most of thost args (and I'm not sure how to set them after-the-fact).

**Comment by tobio** [comment]
Looking at the [tests](https://github.com/campaignmonitor/createsend-ruby/blob/master/test/subscriber_test.rb#L103) can give a good idea on the expectations for inputs. 

In this case, you just need to supply a list of hashes with the subscriber details. Resubscribe and autoresponder options are [method level](https://github.com/campaignmonitor/createsend-ruby/blob/master/lib/createsend/subscriber.rb#L41) parameters.

**Comment by plainlystated** [comment]
Got it, thanks for the info.
